### ISSUE TITLE
Maybe have a "tutorials" section under each topic (as necessary)

### ISSUE THREAD

**Issue by rlahoda** [dpacassi/UltimateDrupalReference#6]
Right now the general structure is to list the main topics and then have the various modules listed underneath and then at the bottom is "video tutorials" and "blog posts" with some tutorials under them. Maybe it would be better to have a specific "tutorials" section under each of the topics, or just have them listed under each module if there's a tutorial specific to it. This would help with discovery for someone not only finding the module they want but also seeing a tutorial listed with it.

Here's an example:

### Forms
- [Webform](https://www.drupal.org/project/webform) - Webform is the module for making forms and surveys in Drupal.
    - [Webform videos on Drupal.org](https://www.drupal.org/docs/8/modules/webform/webform-videos) - A series of videos by the makers of Webform explaining features and tutorials for installing and using the Webform module.

**Comment by dpacassi** [comment]
Nice catch! If we have a video specifically for one listed module, we can add it as sub-list entry to the module entry - just as in your example!

But I would also add it to the _Video tutorials_ section itself (Yeah, I know, duplicate content, but having a list of all different videos is still beneficial I think).

About the _Video tutorials_ section itself, we probably want to add sub-categories.
E.g. following ones:
- General
- Distributions
- Modules
- Themes

That way we can structure the videos a bit more.
WDYT @rlahoda?

**Comment by rlahoda** [comment]
I think that's a great idea. Even having the duplicate information would be ok, I think, because it would mean that the link is in both places people would expect it. I'm planning on adding some additional resources hopefully today so I'll add those changes in when I do.

**Comment by dpacassi** [comment]
Great 👍 
Just ping me if you need any help/assistance!
